version: 0.2
env:
    variables:
        BUILD_FOLDER: "src"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build --${BUILD_ENV}
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes